const assert = require('node:assert/strict')
const P = require('./PresentationModel.js')
assert.equal(P.capacityText({energyFullWh: 51.2, energyDesignWh: 60, energyEstimated: true}), '51.2 Wh / 60.0 Wh (estimate)')
assert.equal(P.capacityText({energyFullWh: 51.2, energyDesignWh: 60, energyEstimated: false}), '51.2 Wh / 60.0 Wh')
assert.equal(P.capacityText({energyFullWh: null}, '57 Wh'), '57 Wh')
assert.equal(P.capacityText({energyFullWh: null, energyDesignWh: 60}), '—')
assert.equal(P.rateText(-10.2), '−10.2 W')
assert.equal(P.rateText(0), '0.0 W')
assert.equal(P.rateText(null), '')
assert.equal(P.rateText(NaN), '')
assert.equal(P.numberText(0), '0')
assert.equal(P.numberText(null), '—')
assert.equal(P.healthText({health:'Good',capacityHealthPercent:85}), 'Good')
assert.equal(P.healthText({capacityHealthPercent:85}), 'Unavailable')
assert.equal(P.capacityHealthText({capacityHealthPercent:85}), '85.0% (estimate)')
assert.equal(P.capacityHealthText({capacityHealthPercent:null}), '—')
console.log('Presentation formatting checks passed.')
